class AddEnglishCountryNames < ActiveRecord::Migration
  def self.up
    Country.find_by_code('AD').update_attribute(:name_en,'Andorra')
    Country.find_by_code('AE').update_attribute(:name_en,'United Arab Emirates')
    Country.find_by_code('AF').update_attribute(:name_en,'Afghanistan')
    Country.find_by_code('AG').update_attribute(:name_en,'Antigua And Barbuda')
    Country.find_by_code('AI').update_attribute(:name_en,'Anguilla')
    Country.find_by_code('AL').update_attribute(:name_en,'Albania')
    Country.find_by_code('AM').update_attribute(:name_en,'Armenia')
    Country.find_by_code('AN').update_attribute(:name_en,'Netherlands Antilles')
    Country.find_by_code('AO').update_attribute(:name_en,'Angola')
    Country.find_by_code('AQ').update_attribute(:name_en,'Antarctica')
    Country.find_by_code('AR').update_attribute(:name_en,'Argentina')
    Country.find_by_code('AS').update_attribute(:name_en,'American Samoa')
    Country.find_by_code('AT').update_attribute(:name_en,'Austria')
    Country.find_by_code('AU').update_attribute(:name_en,'Australia')
    Country.find_by_code('AW').update_attribute(:name_en,'Aruba')
    Country.find_by_code('AZ').update_attribute(:name_en,'Azerbaijan')
    Country.find_by_code('BA').update_attribute(:name_en,'Bosnia And Herzegovina')
    Country.find_by_code('BB').update_attribute(:name_en,'Barbados')
    Country.find_by_code('BD').update_attribute(:name_en,'Bangladesh')
    Country.find_by_code('BE').update_attribute(:name_en,'Belgium')
    Country.find_by_code('BF').update_attribute(:name_en,'Burkina Faso')
    Country.find_by_code('BG').update_attribute(:name_en,'Bulgaria')
    Country.find_by_code('BH').update_attribute(:name_en,'Bahrain')
    Country.find_by_code('BI').update_attribute(:name_en,'Burundi')
    Country.find_by_code('BJ').update_attribute(:name_en,'Benin')
    Country.find_by_code('BM').update_attribute(:name_en,'Bermuda')
    Country.find_by_code('BN').update_attribute(:name_en,'Brunei Darussalam')
    Country.find_by_code('BO').update_attribute(:name_en,'Bolivia')
    Country.find_by_code('BR').update_attribute(:name_en,'Brazil')
    Country.find_by_code('BS').update_attribute(:name_en,'Bahamas')
    Country.find_by_code('BT').update_attribute(:name_en,'Bhutan')
    Country.find_by_code('BV').update_attribute(:name_en,'Bouvet Island')
    Country.find_by_code('BW').update_attribute(:name_en,'Botswana')
    Country.find_by_code('BY').update_attribute(:name_en,'Belarus')
    Country.find_by_code('BZ').update_attribute(:name_en,'Belize')
    Country.find_by_code('CA').update_attribute(:name_en,'Canada')
    Country.find_by_code('CC').update_attribute(:name_en,'Cocos (Keeling) Islands')
    Country.find_by_code('CD').update_attribute(:name_en,'Congo, The Democratic Republic Of The')
    Country.find_by_code('CF').update_attribute(:name_en,'Central African Republic')
    Country.find_by_code('CG').update_attribute(:name_en,'Congo')
    Country.find_by_code('CI').update_attribute(:name_en,"Cote D'ivoire")
    Country.find_by_code('CK').update_attribute(:name_en,'Cook Islands')
    Country.find_by_code('CL').update_attribute(:name_en,'Chile')
    Country.find_by_code('CM').update_attribute(:name_en,'Cameroon')
    Country.find_by_code('CN').update_attribute(:name_en,'China')
    Country.find_by_code('CO').update_attribute(:name_en,'Colombia')
    Country.find_by_code('CR').update_attribute(:name_en,'Costa Rica')
    Country.find_by_code('CU').update_attribute(:name_en,'Cuba')
    Country.find_by_code('CV').update_attribute(:name_en,'Cape Verde')
    Country.find_by_code('CX').update_attribute(:name_en,'Christmas Island')
    Country.find_by_code('CY').update_attribute(:name_en,'Cyprus')
    Country.find_by_code('CZ').update_attribute(:name_en,'Czech Republic')
    Country.find_by_code('DE').update_attribute(:name_en,'Germany')
    Country.find_by_code('DJ').update_attribute(:name_en,'Djibouti')
    Country.find_by_code('DK').update_attribute(:name_en,'Denmark')
    Country.find_by_code('DM').update_attribute(:name_en,'Dominica')
    Country.find_by_code('DO').update_attribute(:name_en,'Dominican Republic')
    Country.find_by_code('DZ').update_attribute(:name_en,'Algeria')
    Country.find_by_code('EC').update_attribute(:name_en,'Ecuador')
    Country.find_by_code('EE').update_attribute(:name_en,'Estonia')
    Country.find_by_code('EG').update_attribute(:name_en,'Egypt')
    Country.find_by_code('EH').update_attribute(:name_en,'Western Sarara')
    Country.find_by_code('ER').update_attribute(:name_en,'Eritrea')
    Country.find_by_code('ES').update_attribute(:name_en,'Spain')
    Country.find_by_code('ET').update_attribute(:name_en,'Ethiopia')
    Country.find_by_code('FI').update_attribute(:name_en,'Finland')
    Country.find_by_code('FJ').update_attribute(:name_en,'Fiji')
    Country.find_by_code('FK').update_attribute(:name_en,'Falkland Islands (Malvinas)')
    Country.find_by_code('FM').update_attribute(:name_en,'Micronesia, Federated States Of')
    Country.find_by_code('FO').update_attribute(:name_en,'Faroe Islands')
    Country.find_by_code('FR').update_attribute(:name_en,'France')
    Country.find_by_code('GA').update_attribute(:name_en,'Gabon')
    Country.find_by_code('GB').update_attribute(:name_en,'United Kingdom')
    Country.find_by_code('GD').update_attribute(:name_en,'Grenada')
    Country.find_by_code('GE').update_attribute(:name_en,'Georgia')
    Country.find_by_code('GF').update_attribute(:name_en,'French Guiana')
    Country.find_by_code('GH').update_attribute(:name_en,'Ghana')
    Country.find_by_code('GI').update_attribute(:name_en,'Gibraltar')
    Country.find_by_code('GL').update_attribute(:name_en,'Greenland')
    Country.find_by_code('GM').update_attribute(:name_en,'Gambia')
    Country.find_by_code('GN').update_attribute(:name_en,'Guinea')
    Country.find_by_code('GP').update_attribute(:name_en,'Guadeloupe')
    Country.find_by_code('GQ').update_attribute(:name_en,'Equatorial Guinea')
    Country.find_by_code('GR').update_attribute(:name_en,'Greece')
    Country.find_by_code('GS').update_attribute(:name_en,'South Georgia And The South Sandwich Islands')
    Country.find_by_code('GT').update_attribute(:name_en,'Guatemala')
    Country.find_by_code('GU').update_attribute(:name_en,'Guam')
    Country.find_by_code('GW').update_attribute(:name_en,'Guinea-Bissau')
    Country.find_by_code('GY').update_attribute(:name_en,'Guyana')
    Country.find_by_code('HK').update_attribute(:name_en,'Hong Kong')
    Country.find_by_code('HM').update_attribute(:name_en,'Heard Island And Mcdonald Islands')
    Country.find_by_code('HN').update_attribute(:name_en,'Honduras')
    Country.find_by_code('HR').update_attribute(:name_en,'Croatia')
    Country.find_by_code('HT').update_attribute(:name_en,'Haiti')
    Country.find_by_code('HU').update_attribute(:name_en,'Hungary')
    Country.find_by_code('CH').update_attribute(:name_en,'Switzerland')
    Country.find_by_code('ID').update_attribute(:name_en,'Indonesia')
    Country.find_by_code('IE').update_attribute(:name_en,'Ireland')
    Country.find_by_code('IL').update_attribute(:name_en,'Israel')
    Country.find_by_code('IN').update_attribute(:name_en,'India')
    Country.find_by_code('IO').update_attribute(:name_en,'British Indian Ocean Territory')
    Country.find_by_code('IQ').update_attribute(:name_en,'Iraq')
    Country.find_by_code('IR').update_attribute(:name_en,'Iran, Islamic Republic Of')
    Country.find_by_code('IS').update_attribute(:name_en,'Iceland')
    Country.find_by_code('IT').update_attribute(:name_en,'Italy')
    Country.find_by_code('JM').update_attribute(:name_en,'Jamaica')
    Country.find_by_code('JO').update_attribute(:name_en,'Jordan')
    Country.find_by_code('JP').update_attribute(:name_en,'Japan')
    Country.find_by_code('KE').update_attribute(:name_en,'Kenya')
    Country.find_by_code('KG').update_attribute(:name_en,'Kyrgyzstan')
    Country.find_by_code('KH').update_attribute(:name_en,'Cambodia')
    Country.find_by_code('KI').update_attribute(:name_en,'Kiribati')
    Country.find_by_code('KM').update_attribute(:name_en,'Comoros')
    Country.find_by_code('KN').update_attribute(:name_en,'Saint Kitts And Nevis')
    Country.find_by_code('KP').update_attribute(:name_en,"Korea, Democratic People's Republic Of")
    Country.find_by_code('KR').update_attribute(:name_en,'Korea, Republic Of')
    Country.find_by_code('KW').update_attribute(:name_en,'Kuwait')
    Country.find_by_code('KY').update_attribute(:name_en,'Cayman Islands')
    Country.find_by_code('KZ').update_attribute(:name_en,'Kazakhstan')
    Country.find_by_code('LA').update_attribute(:name_en,"Lao People's Democratic Republic")
    Country.find_by_code('LB').update_attribute(:name_en,'Lebanon')
    Country.find_by_code('LC').update_attribute(:name_en,'Saint Lucia')
    Country.find_by_code('LI').update_attribute(:name_en,'Liechtenstein')
    Country.find_by_code('LK').update_attribute(:name_en,'Sri Lanka')
    Country.find_by_code('LR').update_attribute(:name_en,'Liberia')
    Country.find_by_code('LS').update_attribute(:name_en,'Lesotho')
    Country.find_by_code('LT').update_attribute(:name_en,'Lithuania')
    Country.find_by_code('LU').update_attribute(:name_en,'Luxembourg')
    Country.find_by_code('LV').update_attribute(:name_en,'Latvia')
    Country.find_by_code('LY').update_attribute(:name_en,'Libyan Arab Jamabiriya')
    Country.find_by_code('MA').update_attribute(:name_en,'Morocco')
    Country.find_by_code('MC').update_attribute(:name_en,'Monaco')
    Country.find_by_code('MD').update_attribute(:name_en,'Moldova, Republic Of')
    Country.find_by_code('MG').update_attribute(:name_en,'Madagascar')
    Country.find_by_code('MH').update_attribute(:name_en,'Marshall Islands')
    Country.find_by_code('MK').update_attribute(:name_en,'Macedonia, The Former Yugoslav Republic Of')
    Country.find_by_code('ML').update_attribute(:name_en,'Mali')
    Country.find_by_code('MM').update_attribute(:name_en,'Myanmar')
    Country.find_by_code('MN').update_attribute(:name_en,'Mongolia')
    Country.find_by_code('MO').update_attribute(:name_en,'Macau')
    Country.find_by_code('MP').update_attribute(:name_en,'Northern Mariana Islands')
    Country.find_by_code('MQ').update_attribute(:name_en,'Martinique')
    Country.find_by_code('MR').update_attribute(:name_en,'Mauritania')
    Country.find_by_code('MS').update_attribute(:name_en,'Montserrat')
    Country.find_by_code('MT').update_attribute(:name_en,'Malta')
    Country.find_by_code('MU').update_attribute(:name_en,'Mauritius')
    Country.find_by_code('MV').update_attribute(:name_en,'Maldives')
    Country.find_by_code('MW').update_attribute(:name_en,'Malawi')
    Country.find_by_code('MX').update_attribute(:name_en,'Mexico')
    Country.find_by_code('MY').update_attribute(:name_en,'Malaysia')
    Country.find_by_code('MZ').update_attribute(:name_en,'Mozambique')
    Country.find_by_code('NA').update_attribute(:name_en,'Namibia')
    Country.find_by_code('NC').update_attribute(:name_en,'New Caledonia')
    Country.find_by_code('NE').update_attribute(:name_en,'Niger')
    Country.find_by_code('NF').update_attribute(:name_en,'Norfolk Island')
    Country.find_by_code('NG').update_attribute(:name_en,'Nigeria')
    Country.find_by_code('NI').update_attribute(:name_en,'Nicaragua')
    Country.find_by_code('NL').update_attribute(:name_en,'Netherlands')
    Country.find_by_code('NO').update_attribute(:name_en,'Norway')
    Country.find_by_code('NP').update_attribute(:name_en,'Nepal')
    Country.find_by_code('NR').update_attribute(:name_en,'Nauru')
    Country.find_by_code('NU').update_attribute(:name_en,'Niue')
    Country.find_by_code('NZ').update_attribute(:name_en,'New Zealand')
    Country.find_by_code('OM').update_attribute(:name_en,'Oman')
    Country.find_by_code('PA').update_attribute(:name_en,'Panama')
    Country.find_by_code('PE').update_attribute(:name_en,'Peru')
    Country.find_by_code('PF').update_attribute(:name_en,'French Polynesia')
    Country.find_by_code('PG').update_attribute(:name_en,'Papua New Guinea')
    Country.find_by_code('PH').update_attribute(:name_en,'Philippines')
    Country.find_by_code('PK').update_attribute(:name_en,'Pakistan')
    Country.find_by_code('PL').update_attribute(:name_en,'Poland')
    Country.find_by_code('PM').update_attribute(:name_en,'Saint Pierre And Miquelon')
    Country.find_by_code('PN').update_attribute(:name_en,'Pitcairn')
    Country.find_by_code('PR').update_attribute(:name_en,'Puerto Rico')
    Country.find_by_code('PS').update_attribute(:name_en,'Palestinian Territory, Occupied')
    Country.find_by_code('PT').update_attribute(:name_en,'Portugal')
    Country.find_by_code('PW').update_attribute(:name_en,'Palau')
    Country.find_by_code('PY').update_attribute(:name_en,'Paraguay')
    Country.find_by_code('QA').update_attribute(:name_en,'Qatar')
    Country.find_by_code('RE').update_attribute(:name_en,'Reunion')
    Country.find_by_code('RO').update_attribute(:name_en,'Romania')
    Country.find_by_code('RU').update_attribute(:name_en,'Russian Federation')
    Country.find_by_code('RW').update_attribute(:name_en,'Rwanda')
    Country.find_by_code('SA').update_attribute(:name_en,'Saudi Arabia')
    Country.find_by_code('SB').update_attribute(:name_en,'Solomon Islands')
    Country.find_by_code('SC').update_attribute(:name_en,'Seychelles')
    Country.find_by_code('SD').update_attribute(:name_en,'Sudan')
    Country.find_by_code('SE').update_attribute(:name_en,'Sweden')
    Country.find_by_code('SG').update_attribute(:name_en,'Singapore')
    Country.find_by_code('SH').update_attribute(:name_en,'Saint Helena')
    Country.find_by_code('SI').update_attribute(:name_en,'Slovenia')
    Country.find_by_code('SJ').update_attribute(:name_en,'Svalbard And Jan Mayen')
    Country.find_by_code('SK').update_attribute(:name_en,'Slovakia')
    Country.find_by_code('SL').update_attribute(:name_en,'Sierra Leone')
    Country.find_by_code('SM').update_attribute(:name_en,'San Marino')
    Country.find_by_code('SN').update_attribute(:name_en,'Senegal')
    Country.find_by_code('SO').update_attribute(:name_en,'Somalia')
    Country.find_by_code('SR').update_attribute(:name_en,'Suriname')
    Country.find_by_code('ST').update_attribute(:name_en,'Sao Tome And Principe')
    Country.find_by_code('SV').update_attribute(:name_en,'El Salvador')
    Country.find_by_code('SY').update_attribute(:name_en,'Syrian Arab Republic')
    Country.find_by_code('SZ').update_attribute(:name_en,'Swaziland')
    Country.find_by_code('TC').update_attribute(:name_en,'Turks And Caicos Islands')
    Country.find_by_code('TD').update_attribute(:name_en,'Chad')
    Country.find_by_code('TF').update_attribute(:name_en,'French Southern Territories')
    Country.find_by_code('TG').update_attribute(:name_en,'Togo')
    Country.find_by_code('TH').update_attribute(:name_en,'Thailand')
    Country.find_by_code('TJ').update_attribute(:name_en,'Tajikistan')
    Country.find_by_code('TK').update_attribute(:name_en,'Tokelau')
    Country.find_by_code('TM').update_attribute(:name_en,'Turkmenistan')
    Country.find_by_code('TN').update_attribute(:name_en,'Tunisia')
    Country.find_by_code('TO').update_attribute(:name_en,'Tonga')
#    Country.find_by_code('TP').update_attribute(:name_en,'East Timor')
    Country.find_by_code('TR').update_attribute(:name_en,'Turkey')
    Country.find_by_code('TT').update_attribute(:name_en,'Trinidad And Tobago')
    Country.find_by_code('TV').update_attribute(:name_en,'Tuvalu')
    Country.find_by_code('TW').update_attribute(:name_en,'Taiwan, Province Of China')
    Country.find_by_code('TZ').update_attribute(:name_en,'Tanzania, United Republic Of')
    Country.find_by_code('UA').update_attribute(:name_en,'Ukraine')
    Country.find_by_code('UG').update_attribute(:name_en,'Uganda')
    Country.find_by_code('UM').update_attribute(:name_en,'United States Minor Outlying Islands')
    Country.find_by_code('US').update_attribute(:name_en,'United States')
    Country.find_by_code('UY').update_attribute(:name_en,'Uruguay')
    Country.find_by_code('UZ').update_attribute(:name_en,'Uzbekistan')
    Country.find_by_code('VA').update_attribute(:name_en,'Holy See (Vatican City State)')
    Country.find_by_code('VC').update_attribute(:name_en,'Saint Vincent And The Grenadines')
    Country.find_by_code('VE').update_attribute(:name_en,'Venezuela')
    Country.find_by_code('VG').update_attribute(:name_en,'Virgin Islands, British')
    Country.find_by_code('VI').update_attribute(:name_en,'Virgin Islands, U.S.')
    Country.find_by_code('VN').update_attribute(:name_en,'Viet Nam')
    Country.find_by_code('VU').update_attribute(:name_en,'Vanuatu')
    Country.find_by_code('WF').update_attribute(:name_en,'Wallis And Futuna')
    Country.find_by_code('WS').update_attribute(:name_en,'Samoa')
    Country.find_by_code('YE').update_attribute(:name_en,'Yemen')
    Country.find_by_code('YT').update_attribute(:name_en,'Mayotte')
#    Country.find_by_code('YU').update_attribute(:name_en,'Yugoslavia')
    Country.find_by_code('ZA').update_attribute(:name_en,'South Africa')
    Country.find_by_code('ZM').update_attribute(:name_en,'Zambia')
    Country.find_by_code('ZW').update_attribute(:name_en,'Zimbabwe')
  rescue => e
    puts e.backtrace
  end

  def self.down
  end
end
